# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='Owner',
            new_name='owner',
        ),
    ]
