# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160215_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='/Users/alexmwaleh/media_cdn/%Y/%m/%d'),
        ),
    ]
