# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160220_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'get_latest_by': 'modified_on'},
        ),
    ]
