# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160220_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={},
        ),
    ]
