# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ('-modified_on',)},
        ),
    ]
