# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160222_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='effects',
        ),
    ]
