# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_uploadfile_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='edited',
            field=models.SmallIntegerField(default=0),
        ),
    ]
