# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 08:43
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_uploadfile_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profile/%Y/%m/%d'),
        ),
    ]
